config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :posts do
    resources :comments
  end
  resources :labels

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :edit]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def edit; end

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id, :comment_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<% unless @comments.count.nil? %>
<%= @comments_count %>

<% @comments.each_with_index do |comment, i| %>
<p>

<%= "No.#{h(i + 1)}" %>
  <strong><%= comment.body %>:</strong>
  <%= comment.user.email %>
  <%= link_to 'Delete', post_comment_path(:id => comment.id, :post_id => @post.id ),method: :delete, class: "button is-danger", data: { confirm: 'Do you want to delete?' } %>
  <%= link_to 'Edit', edit_post_comment_path(:id => comment.id, :post_id => @post.id ), class: "button is-danger", data: { confirm: 'Do you want to edit?' } %>
</p>
<% end %>
<% else %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
<%= f.text_field :body %>
<%= f.submit%>
<% end %>