config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :posts do
    resources :comments
  end
  resources :labels

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

end

app/models/label.rb
class Label < ApplicationRecord
  has_many :posts, through: :posts_labels
  has_many :posts_labels
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  def index
    @labels = Label.all
  end

  def show
  end

  def new
    @label = Label.new
  end

  def edit
  end

  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_label
      @label = Label.find(params[:id])
    end

    def label_params
      params.require(:label).permit(:tag)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.tag %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tag:</strong>
  <%= @label.tag %>
</p>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>