config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :posts do
    resources :comments
  end
  resources :labels

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :posts_labels
  has_many :labels, through: :posts_labels
  has_many :comments
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    @comment = Comment.new
  end

  def show
    @comments = @post.comments
    @comment = Comment.new
    @comments_count = Comment.where(post_id: @post.id).count
  end

  def new
    @post = Post.new
  end

  def edit
    @comments = @post.comments
    post_id = @post.id
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def update
    user_id = current_user.id
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      redirect_to post_path(@post)
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:error, :user_id, :posts_label_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :error %>
    <%= f.hidden_field :user_id, value:current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to 'Posts', new_post_path %></h1>
<%= render 'weather/weather' %>

<table>
  <thead>
    <tr>
      <th>ErrorCode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user.id %></td>
        <td><%= markdown(post.error.truncate(50)).html_safe %></td>
        <td><%= post.id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<strong><h1><%= link_to 'ErrorCode', posts_path %></h1></strong>
<%= link_to '編集する', edit_post_path(@post) %>

<%= markdown(@post.error).html_safe %>
<p><%= render 'comments/comments', post: @post   %></p><br>
<%= render 'comments/form', post: @post  %>